-- Supabase : table du classement
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  pseudo text not null,
  score integer not null check (score >= 0),
  correct integer not null check (correct between 0 and 20),
  lives integer not null check (lives between 0 and 3),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

create policy "public can read scores"
on public.scores for select
to anon
using (true);

create policy "public can insert scores"
on public.scores for insert
to anon
with check (
  char_length(pseudo) between 2 and 18
  and score >= 0
  and correct between 0 and 20
  and lives between 0 and 3
);

-- Pour un vrai jeu public, ajoute ensuite une protection anti-triche
-- côté serveur si le classement doit être considéré comme compétitif.
